[package]
name = "rust-dashboard-app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
egui = "0.30.0"
eframe = "0.30.0"
serde = "1.0.217"
serde_json = "1.0.138"
egui_extras = "0.30.0"
rust-i18n = "3.1.2"